version: '3.9'

services:
  app:
    container_name: webapp-anton
    build: ./app  
    restart: always
    ports:
      - "5004:5004"  # Expose Flask app on port 5004
    env_file:
      - ./app/.env
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./app/logs:/home/logs
    secrets:
      - mysql-user
      - mysql-user-password
      - mysql-database
      - secret-key
    networks:
      - apps-network

networks:
  apps-network:
    external: true
    name: webapps_network 

secrets:
  mysql-user:
    file: ./secrets/mysql-user
  mysql-user-password:
    file: ./secrets/mysql-user-password
  mysql-database:
    file: ./secrets/mysql-database
  secret-key:
    file: ./secrets/secret-key

